name: 'bambu_print_history'
version: '1.0.0'
config-version: 2

profile: 'bambu_print_history'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bambu_print_history:
    bronze:
      +materialized: table
